name: Fast DDS Discovery Server Ubuntu CI (nightly)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  nightly-ubuntu-ci-master:
    uses: eProsima/Discovery-Server/.github/workflows/reusable-ubuntu-ci.yml@master
    with:
      # It would be desirable to have a matrix of ubuntu OS for this job, but due to the issue opened in this ticket:
      # https://github.com/orgs/community/discussions/128118 , it has been set as a single OS job.
      os-version: 'ubuntu-22.04'
      label: 'nightly-ubuntu-ci-master'
      discovery-server-branch: 'master'
      fastdds-branch: 'master'
      ctest-args: "-LE xfail"
      run-build: true
      run-tests: true
      use-ccache: false

  nightly-ubuntu-ci-v1_2_2:
    strategy:
      fail-fast: false
      matrix:
        fastdds-branch:
         - '2.14.x'
         - '2.13.x'
    uses: eProsima/Discovery-Server/.github/workflows/reusable-ubuntu-ci.yml@1.2.x
    with:
      # It would be desirable to have a matrix of ubuntu OS for this job, but due to the issue opened in this ticket:
      # https://github.com/orgs/community/discussions/128118 , it has been set as a single OS job.
      os-version: 'ubuntu-22.04'
      label: 'nightly-ubuntu-ci-v1.2.2-${{ matrix.fastdds-branch }}'
      discovery-server-branch: 'v1.2.2'
      fastdds-branch: ${{ matrix.fastdds-branch }}
      ctest-args: "-LE xfail"
      run-build: true
      run-tests: true
      use-ccache: false

  nightly-ubuntu-ci-v1_2_1:
    strategy:
      fail-fast: false
      matrix:
        setup:
          - os-version: 'ubuntu-22.04'
            fastdds-branch: '2.10.x'
          - os-version: 'ubuntu-20.04'
            fastdds-branch: '2.6.x'
    uses: eProsima/Discovery-Server/.github/workflows/reusable-ubuntu-ci.yml@1.2.x
    with:
      os-version: ${{ matrix.setup.os-version }}
      label: 'nightly-ubuntu-ci-v1.2.1-${{ matrix.setup.fastdds-branch }}'
      discovery-server-branch: 'v1.2.1'
      fastdds-branch: ${{ matrix.setup.fastdds-branch }}
      ctest-args: "-LE xfail"
      run-build: true
      run-tests: true
      use-ccache: false
