name: Fast DDS Discovery Server Ubuntu CI reusable workflow

on:
  workflow_call:
    inputs:
      os-version:
        description: 'The OS image for the workflow'
        required: false
        default: 'ubuntu-22.04'
        type: string
      label:
        description: 'ID associated to the workflow'
        required: true
        type: string
      colcon-args:
        description: 'Extra arguments for colcon cli'
        required: false
        type: string
      cmake-args:
        description: 'Extra arguments for cmake cli'
        required: false
        type: string
      ctest-args:
        description: 'Extra arguments for ctest cli'
        required: false
        type: string
      discovery-server-branch:
        description: 'Branch or tag of Discovery Server repository'
        required: true
        type: string
      fastdds-branch:
        description: 'Branch or tag of Fast DDS repository'
        required: true
        type: string
      run-build:
        description: 'Build Fast DDS Discovery Server (CI skipped otherwise)'
        required: false
        type: boolean
        default: true
      run-tests:
        description: 'Run test suite of Fast DDS Discovery Server'
        required: false
        type: boolean
        default: true
      use-ccache:
        description: 'Use CCache to speed up the build'
        required: false
        type: boolean
        default: false
env:
    colcon-build-default-cmake-args: '-DCMAKE_CXX_FLAGS="-Werror -Wall -Wextra -Wpedantic -Wunused-value -Woverloaded-virtual"'
defaults:
  run:
    shell: bash

jobs:
  discovery_server_build:
    runs-on: ${{ inputs.os-version }}
    if: ${{ inputs.run-build == true }}
    strategy:
      fail-fast: false
      matrix:
        cmake-build-type:
          - 'RelWithDebInfo'
    steps:
      - name: Add ci-pending label if PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: eProsima/eProsima-CI/external/add_labels@v0
        with:
          labels: ci-pending
          number: ${{ github.event.number }}
          repo: eProsima/Discovery-Server

      - name: Sync eProsima/Discovery-Server repository
        uses: eProsima/eProsima-CI/external/checkout@v0
        with:
          path: src/discovery_server
          ref: ${{ inputs.discovery-server-branch }}

      - name: Install Fix Python version
        uses: eProsima/eProsima-CI/external/setup-python@v0
        with:
          python-version: '3.11'

      - name: Get minimum supported version of CMake
        uses: eProsima/eProsima-CI/external/get-cmake@v0
        with:
          cmakeVersion: '3.22.6'

      - name: Install apt dependencies
        uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@v0
        with:
          packages: libasio-dev libtinyxml2-dev libssl-dev
          update: false
          upgrade: false

      - name: Install colcon
        uses: eProsima/eProsima-CI/ubuntu/install_colcon@v0

      - name: Install Python dependencies
        uses: eProsima/eProsima-CI/multiplatform/install_python_packages@v0
        with:
          packages: vcstool xmlschema xmltodict==0.13.0 jsondiff==2.0.0 pandas==1.5.2
          upgrade: false

      - name: Setup CCache
        uses: eProsima/eProsima-CI/external/setup-ccache-action@v0
        if: ${{ inputs.use-ccache == true }}
        with:
          api_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Fast DDS branch
        id: get_fastdds_branch
        uses: eProsima/eProsima-CI/ubuntu/get_related_branch_from_repo@v0
        with:
          remote_repository: eProsima/Fast-DDS
          fallback_branch: ${{ inputs.fastdds-branch }}

      - name: Download Fast DDS repo
        uses: eProsima/eProsima-CI/external/checkout@v0
        with:
          repository: eProsima/Fast-DDS
          path: src/fastdds
          ref: ${{ steps.get_fastdds_branch.outputs.deduced_branch }}

      - name: Fetch Fast DDS dependencies
        uses: eProsima/eProsima-CI/multiplatform/vcs_import@v0
        with:
          vcs_repos_file: ${{ github.workspace }}/src/fastdds/fastdds.repos
          destination_workspace: src
          skip_existing: 'true'

      - name: Colcon build
        continue-on-error: false
        uses: eProsima/eProsima-CI/multiplatform/colcon_build@v0
        with:
          colcon_meta_file: ${{ github.workspace }}/src/discovery_server/.github/workflows/config/build.meta
          colcon_build_args: ${{ inputs.colcon-args }}
          cmake_args: ${{ inputs.cmake-args }}
          cmake_args_default: ${{ env.colcon-build-default-cmake-args }}
          cmake_build_type: ${{ matrix.cmake-build-type }}
          workspace: ${{ github.workspace }}

      - name: 'Tar workspace'
        run: tar -cvf github_ws.tar ${{ github.workspace }}

      - name: Upload build artifacts
        uses: eProsima/eProsima-CI/external/upload-artifact@v0
        with:
          name: discovery_server_build_${{ inputs.label }}
          path: github_ws.tar

  discovery_server_tests:
    needs: discovery_server_build
    runs-on: ${{ inputs.os-version }}
    strategy:
      fail-fast: false
      matrix:
        cmake-build-type:
          - 'RelWithDebInfo'
    steps:
      - name: Download build artifacts
        uses: eProsima/eProsima-CI/external/download-artifact@v0
        with:
          name: discovery_server_build_${{ inputs.label }}

      - name: 'Restore workspace'
        run: tar -xvf github_ws.tar -C ${{ github.workspace }} --strip-components=5

      - name: Install Fix Python version
        uses: eProsima/eProsima-CI/external/setup-python@v0
        with:
          python-version: '3.11'

      - name: Get minimum supported version of CMake
        uses: eProsima/eProsima-CI/external/get-cmake@v0
        with:
          cmakeVersion: '3.22.6'

      - name: Install apt dependencies
        uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@v0
        with:
          packages: libasio-dev libtinyxml2-dev libssl-dev
          update: false
          upgrade: false

      - name: Install colcon
        uses: eProsima/eProsima-CI/ubuntu/install_colcon@v0

      - name: Install Python dependencies
        uses: eProsima/eProsima-CI/multiplatform/install_python_packages@v0
        with:
          packages: vcstool xmlschema xmltodict==0.13.0 jsondiff==2.0.0 pandas==1.5.2
          upgrade: false

      - name: Setup CCache
        uses: eProsima/eProsima-CI/external/setup-ccache-action@v0
        if: ${{ inputs.use-ccache == true }}
        with:
          api_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Fast DDS CI dependencies
        uses: eProsima/eProsima-CI/multiplatform/vcs_import@v0
        with:
          vcs_repos_file: ${{ github.workspace }}/src/discovery_server/.github/workflows/config/test.repos
          destination_workspace: src
          skip_existing: 'true'

      - name: Colcon build
        continue-on-error: false
        uses: eProsima/eProsima-CI/multiplatform/colcon_build@v0
        with:
          colcon_meta_file: ${{ github.workspace }}/src/discovery_server/.github/workflows/config/build.meta ${{ github.workspace }}/src/discovery_server/.github/workflows/config/test.meta
          colcon_build_args: ${{ inputs.colcon-args }}
          cmake_args: ${{ inputs.cmake-args }}
          cmake_args_default: ${{ env.colcon-build-default-cmake-args }}
          cmake_build_type: ${{ matrix.cmake-build-type }}
          workspace: ${{ github.workspace }}

      - name: Colcon test
        id: discovery_server_test
        if: ${{ inputs.run-tests == true }}
        uses: eProsima/eProsima-CI/multiplatform/colcon_test@v0
        with:
          colcon_meta_file: ${{ github.workspace }}/src/discovery_server/.github/workflows/config/test.meta
          colcon_test_args: ${{ inputs.colcon-args }}
          colcon_test_args_default: --event-handlers=console_direct+
          ctest_args: ${{ inputs.ctest-args }}
          packages_names: discovery-server
          workspace: ${{ github.workspace }}
          workspace_dependencies: ''
          test_report_artifact: ${{ format('test_report_{0}_{1}_{2}', inputs.label, github.job, join(matrix.*, '_')) }}

      - name: Test summary
        uses: eProsima/eProsima-CI/multiplatform/junit_summary@v0
        if: ${{ !cancelled() && inputs.run-tests == true }}
        with:
          junit_reports_dir: "${{ steps.discovery_server_test.outputs.ctest_results_path }}"
          print_summary: 'True'
          show_failed: 'True'
          show_disabled: 'False'
          show_skipped: 'False'
